// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct URL for migrations, accelerate URL for runtime
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
